### ISSUE TITLE
Move language switcher down on mobile

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/resources-ressources#193]
![Screen Shot 2022-08-03 at 2 29 46 PM](https://user-images.githubusercontent.com/38330843/182682961-b1c21749-8e12-41aa-a525-32410f1719ff.png)

**Comment by dylanzheng94** [comment]
@anikbrazeau Could you verify this has been fixed ... we believe it's resolved now thank you

**Comment by anikbrazeau** [comment]
Just tested on my phone and this is still an issue in production: 

![image](https://user-images.githubusercontent.com/38330843/196260407-f0ddd226-b429-42d8-8ce7-06bc27e1644c.png)

Looks good on staging? Perhaps this PR fixes the issue everywhere? https://github.com/cds-snc/resources-ressources/pull/239

**Comment by dylanzheng94** [comment]
Language switcher has been moved down

**Comment by daine** [comment]
@dylanzheng94 @anikbrazeau I'm closing this as PR #239 has now been merged
