### ISSUE TITLE
Linking resources in draft form breaks display/deployment of starting point "published" resource

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/resources-ressources#313]
# Adding related resources by linking "drafts" breaks the site when deployed.

Something to consider for future is whether we could link up resources and simply hide them until they are ready to be published. That way a lot of the work could be done proactively to place a resource within a topic or within another resource's related resources before the content is finalized and published. In an ideal world, this would allow us to move and iterate more quickly.

In the present, a "Draft resource" cannot be linked to any entries until published.

<img width="426" alt="Screenshot 2022-11-10 at 10 47 42 AM" src="https://user-images.githubusercontent.com/38330843/201141246-e2ea8da3-b261-496d-94e2-cc15bf64f780.png">

**Comment by dylanzheng94** [comment]
resolved

**Comment by dylanzheng94** [comment]
Stumbled upon this issue again.
Linking a draft resource to a topic causes the topic page to break.

**Comment by anikbrazeau** [comment]
This is still an issue. When a link to a draft is published, the initial page that links out will break completely.

<img width="1284" alt="Screenshot 2023-01-25 at 8 28 35 AM" src="https://user-images.githubusercontent.com/38330843/214576496-073973f1-7ccb-4763-993a-46e11f030ce7.png">

Band-aid fix: temporarily hidden in production (by removing the link to draft in Contentful and redeploying)

**Comment by dylanzheng94** [comment]
Fixed
